Repository kommitters/elixir_xdr, pull requests merged in 2022-07, with the labels that each got.

#45 ADD: automate publishing new release using CD
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 👍 Feature

#53 Add security policy to repository
  SECURITY.md
Labels: 📖 Documentation

#54 Prepare release v0.3.1
  CHANGELOG.md
  README.md
  mix.exs
Labels: 🚀 Next release
